### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by g992** [ologn-tech/buildroot-rv1106#1]
Hi, I just started learning buildroot, can you tell me how to build an image for RV1106G3? I didn't find it in the list of boards to build through make <config_name>

**Comment by qhuyduong** [comment]
Hi, 
currently only luckfox pico boards (SPI NOR) are supported.
You can build an image for luckfox pico max board (RV1106G3) by running:
```
make luckfox_pico_max_defconfig
make
```

You can even add support for your board by referencing luckfox_pico_max_defconfig file and board/luckfox-pico folder

**Comment by g992** [comment]
Maybe i do something wrong (?)
I just load defcondig and run make.

```
  DTC     arch/arm/boot/dts/rv1106g-luckfox-pico-max.dtb
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  Kernel: arch/arm/boot/Image is ready
  GZIP    arch/arm/boot/Image.gz
  Kernel: arch/arm/boot/zImage is ready
  Kernel: arch/arm/boot/Image.gz is ready
  Image:  resource.img (with rv1106g-luckfox-pico-max.dtb logo.bmp logo_kernel.bmp) is ready
"mkimage" command not found - U-Boot images will not be built
make[1]: *** [arch/arm/Makefile:374: rv1106g-luckfox-pico-max.img] Error 1
make[1]: Leaving directory '/root/buildroot-rv1106/output/build/linux-24ab4f26ef4270d678595aee738f15a21c7338d3'
make: *** [package/pkg-generic.mk:283: /root/buildroot-rv1106/output/build/linux-24ab4f26ef4270d678595aee738f15a21c7338d3/.stamp_built] Error 2
```

**Comment by g992** [comment]
maybe i figured out what the problem was, i was missing u-boot-tools, i didn't find them in the luckfox sdk requirements list

**Comment by qhuyduong** [comment]
@g992 yes you need to manually install u-boot-tools. luckfox sdk has uboot tools included.

**Comment by g992** [comment]
And what should I do in order to flash the RV1106 with Emmc (or sdcard)? Will the build process be different? Or difference only in flashing process?
