### ISSUE TITLE
RNDIS Connection

### ISSUE THREAD

**Issue by g992** [ologn-tech/buildroot-rv1106#2]
Hi! I am trying to implement an RNDIS connection, but I get an error on the windows side (everything is ok on the linux side, I tried it on ubuntu 22). I upgraded your S49usbgadget script, can you tell me where I could have made a mistake? https://gist.github.com/g992/bf3356ac6dc55ecaef07ca17cf9f07b7

**Comment by qhuyduong** [comment]
We switched to use NCM because it is natively supported by multiple OSes (Linux, Windows, macOS, iOS). 
You can revert this commit to have RNDIS https://github.com/ologn-tech/buildroot-rv1106/commit/ef5e0dd1a6bc4afd270860139c679036f184ce25

**Comment by g992** [comment]
in win10, the system does not automatically detect the NCM device driver, for its correct operation, it is required to select it manually, and rndis works when connected
Thank you so much for your help!
